name: schic-scvi-3d
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.7.*,>=3.8.*
  - numpy>=1.11.*,>=1.11.3
  - scanpy>=1.4.*
  - pandas>=0.21.0,>=0.23.0
  - anndata>=0.7.*
  - scvi-tools==0.14.5
  - joblib
  - scikit-learn